package com.sun.corba.se.ActivationIDL;


/**
* com/sun/corba/se/ActivationIDL/Repository.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../../../../../../src/share/classes/com/sun/corba/se/ActivationIDL/activation.idl
* Monday, September 30, 2002 1:50:46 AM PDT
*/

public interface Repository extends RepositoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Repository
